name: dpv_slam
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip
  - python=3.10
  - pytorch=2.3.1
  - pytorch-scatter=2.1.2
  # - pytorch-cuda=12.1
  - pytorch-cuda=11.8
  # - torchvision=0.18
  - torchvision=0.18.1
  - pip:
    - tensorboard
    - numba
    - tqdm
    - einops
    - pypose
    - kornia
    - numpy==1.26.4
    - plyfile
    - evo
    - opencv-python
    - yacs